### ISSUE TITLE
speed test not working

### ISSUE THREAD

**Issue by gktval** [geerlingguy/internet-monitoring#18] opened 2021-06-22 18:31 UTC
I am having a hard time getting the speed test to work. This is my first time working with docker and grafana-as a result I am unsure how import the speed-test portion into the dashboard. When I navigate to /targets, I can see that it is down. 

![2021-06-22-123108_1920x1080_scrot](https://user-images.githubusercontent.com/7605046/122980348-c2dee300-d355-11eb-87e9-a86718f45329.png)

Any help? Thanks

**Comment by geerlingguy** [comment] 2021-06-22 19:15
@gktval - I'm guessing you're running into this issue: https://github.com/geerlingguy/internet-monitoring/issues/17

Can you try the instructions here for updating libseccomp2 as outlined in [this blog post](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/)?

**Comment by geerlingguy** [comment] 2021-06-22 19:22
Marking as a duplicate of #17.

**Closed as completed by geerlingguy** 2021-06-22 19:22 UTC
Labels: duplicate

**Comment by CyrilPaulus** [comment] 2021-06-23 19:49
I have the same problem no speedtest info on Grafana, http://localhost:9090/targets show me an unknown status for speedtest but http://localhost:9798/metrics output the speedtest result.

I'm running this on a desktop computer so I don't think it's linked to the other issue.

**Comment by CyrilPaulus** [comment] 2021-06-23 19:59
My bad it's working, it's just that with the default scrape_time of 30 minutes you have to wait a little bit.
I changed it to 1 minute to test and had to let it take multiple samples before showing any data.

**Comment by geerlingguy** [comment] 2021-06-23 20:06
@CyrilPaulus - Yeah, that's the downside to not having a frequent interval. It would be nice if the gauges could show something different in the beginning like "please wait for data to be available" but as it is, they just show their 'N/A' state since there's nothing to display yet.
